apiVersion: v2
name: bn-project
description: BN Project Helm Charts
type: application
icon: https://example.com/path/to/icon.png
# Helm chart version
version: 1.1.32

# BN Project version
appVersion: "0.0.1"

dependencies:
  - name: bn-client
    version: 0.1.0
  - name: identityservice
    version: 0.1.0
  - name: alpacaservice
    version: 0.1.0
  - name: strategyservice
    version: 0.1.0
  - name: notificationservice
    version: 0.1.0
  - name: finaiservice
    version: 0.1.0
