# Default values for alpacaservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "ulihdocker/alpacaservice"
  pullPolicy: Always
  tag: "latest"

nameOverride: "alpacaservice"
fullnameOverride: "alpacaservice"

service:
  type: ClusterIP
  port: 5130
  targetPort: 5130    
  selector:
    app: alpacaservice
proxy: edge

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 5     
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15  
  periodSeconds: 5

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false

ingress:
  enabled: false

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
